Add document for TME-1430 cf buildpack migration
pivotal/docs-tas-adapter pull request #13
Opened 2022-01-05 21:42 UTC by gnovv

Added a document for migrating from CF Buildpacks to Buildpacks v3.

Co-authored-by: Andrew Costa <ancosta@vmware.com>

2022-01-05 21:44 UTC, gnovv commented
@tcdowney @emalm we wrote this barebones document to describe requirements for migrating from cf buildpacks to v3 buildpacks. We kept it as mostly an index to other documentation pages because we wanted to limit the amount of maintenance and copy-pasting required moving forward.

2022-01-06 18:06 UTC, emalm requested changes
In general, let's get the buildpack details from Tanzu-commercial installations (TAS and TAP) instead of OSS-based installations. I'm happy to make some prose edits around those details once we have them.

2022-01-06 19:06 UTC, gnovv commented on buildpack-migration.md
> +```
@davewalter helped me claim a TAS environment and we updated the list and removed the zip files

2022-01-06 19:06 UTC, gnovv commented on buildpack-migration.md
> +|procfile |https://github.com/paketo-buildpacks/procfile|
Changed the old yaml to use yours

2022-01-06 19:28 UTC, merged