Add the role management commands to CLI docs
pivotal/docs-tas-adapter pull request #94
Opened 2023-04-14 21:12 UTC by matt-royal

Also add a link to the existing metadata section, which was accidentally omitted.

2023-04-18 21:58 UTC, HenryBorys commented
Hi @emalm, waiting on your review for this one. Thanks.

2023-04-18 22:04 UTC, HenryBorys commented
@matt-royal What versions does this apply to? Just main?

2023-04-18 22:08 UTC, matt-royal commented
Hi @HenryBorys. This PR applies to both main and 1.2. I believe that's true for all of the PRs to main, since there is no 1-2 docs branch and main hasn't diverged much from 1.2 yet.

2023-04-20 00:01 UTC, HenryBorys commented
@matt-royal Yep, main and 1.2 are the same for now. What I'm wondering is whether the PR also applies to previous versions, which is often the case. It's helpful, even if it doesn't, to note as much in the PR so I don't wonder and ask. Thanks. BTW, do we need @emalm to review before merging?

2023-04-20 01:03 UTC, julian-hj requested changes

2023-04-20 01:03 UTC, julian-hj commented on supported-cf-cli-commands.md
> +This section describes the operations for adding and removing roles that Application Service Adapter supports.
Are we currently supporting any roles other than "SpaceDeveloper"? If not, it seems a bit odd to claim that we support `set-org-role`

2023-04-20 16:58 UTC, tcdowney commented on supported-cf-cli-commands.md
> +These commands work for both Kubernetes users and Kubernetes service accounts. When dealing with service accounts,
Addressed in https://github.com/pivotal/docs-tas-adapter/pull/94/commits/b1953157f830be253fd3e60749dfc0c5aa1fcaf1

2023-04-20 17:23 UTC, julian-hj approved these changes

2023-04-20 17:26 UTC, tcdowney approved these changes

2023-04-20 17:38 UTC, merged